version: 2.1

orbs:
  samvera: samvera/circleci-orb@1

jobs:
  bundle_lint_test:
    parameters:
      ruby_version:
        type: string
      project:
        type: string
      bundler_version:
        type: string
        default: 2.3.6

    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>

    steps:
      - samvera/cached_checkout

      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>

      - samvera/rubocop

workflows:
  version: 2
  ci:
    jobs:
      - bundle_lint_test:
          project: bixby
          name: ruby2-6
          ruby_version: 2.6.9

      - bundle_lint_test:
          project: bixby
          name: ruby2-7
          ruby_version: 2.7.5

      - bundle_lint_test:
          project: bixby
          name: ruby3-0
          ruby_version: 3.0.3
